### ISSUE TITLE
Add the ability to disable the implicit `std` dependency in `Forc.toml`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1150]
Follow-up from #1137, which removes the need to explicitly add `std` as a dependency.

**Comment by mitchmindtree** [comment]
I'm imagining this as a field under the `[project]` table along the lines of `implicit-std` where it defaults to `true`.

Disabling the implicit `std` import would then look like:

```toml
[project]
# other fields...
implicit-std = false
```
