### ISSUE TITLE
Create a `forc-test` lib crate that re-exports crates required for the test harness generated by `forc init`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#1345]
We should consider creating a `forc-test` (or `fuels-test` or `sway-test`?) lib crate that re-exports the necessary dependencies to get a `forc test` harness up and running. There are two main motivations that come to mind:

## 1. Reduce verbosity in `forc init` generated test manifest.

Currently, the dependency table of the generated `Forc.toml` looks like this:

```toml
[dependencies]
fuel-gql-client = {{ version = "0.5", default-features = false }}
fuel-tx = "0.7"
fuels-abigen-macro = "0.9"
fuels-contract = "0.9"
fuels-core = "0.9"
fuels-signers = "0.9"
rand = "0.8"
tokio = {{ version = "1.12", features = ["rt", "macros"] }}
```

This is rather verbose and possibly a bit scary for new Sway users. It would be nice if the generated manifest looked more like:

```toml
[dependencies]
forc-test = "0.9.1"
```

In harness code, importing would look similar. The following:

```rust
use fuel_tx::{ContractId, Salt};
use fuels_abigen_macro::abigen;
use fuels_contract::{contract::Contract, parameters::TxParameters};
use fuels_signers::util::test_helpers;
```

would become:

```rust
use forc_test::{
    fuel_tx::{ContractId, Salt};
    fuels_abigen_macro::abigen;
    fuels_contract::{contract::Contract, parameters::TxParameters};
    fuels_signers::util::test_helpers;
};
```

and so on.

Seeing as versions are sync'd across the sway repository, the actual version specified in the generated manifest could be retrieved from forc's own version using the `clap::crate_version!` macro (similar to how we do for the `git` tag used to fetch the `std` lib).

## 2. Make it easier to ensure Rust version compatibility

We could also add this new `forc-test` crate as a dependency of `forc`. This would mean that:

1. We can guarantee that the `forc`'s `rust_version` is able to build the harness code that it generates. Related:
   - #1239 
   - #1333
3. Users can easily determine if their is a disparity between their harness' code and the `forc` version they're currently using by comparing `forc --version` to the `forc-test = "<version>"` in their harness toml. I can imagine this happening a lot where a user might have updated their `forc` multiple times since beginning a sway project.

---

@adlerjohn @digorithm @JoshuaBatty thoughts?
