### ISSUE TITLE
In the test infra, adding a dependency that points to the incorrect location triggers an odd error, sometimes leading to false-positive

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1612]
inside of the `test/src/e2e_vm_tests/test_programs/should_fail/X/Forc.toml` if you incorrectly have the `core` dependency pointing to the wrong location:

```toml
[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "enum_if_let_invalid_variable"

[dependencies]
core = { path = "../../../../../../../sway-lib-core" }
```

when it _should be_:

```toml
[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "enum_if_let_invalid_variable"

[dependencies]
#                         ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
core = { path = "../../../../../../sway-lib-core" }
```

it gives a misleading error:

```bash
 Compiling should_fail/enum_if_let_invalid_variable
  Creating a new `Forc.lock` file. (Cause: lock file did not exist)
_________________________________
Tests passed.
1 tests run (158 skipped)
```

and it repeats this error every time you run the test. In the case of the `should_fail` tests, this produces a false positive.
