### ISSUE TITLE
Duplicate or conflicting dependency declarations should produce a warning or error

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#1645]
Currently adding a duplicate or conflicting dependency to `Forc.toml` does not produce any error or warning. The behavior is ambiguous (which declaration to use is not clear) thus we may want to produce an error.

**Examples**
---

**Duplicate entries:**

```
[dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
```

**Conflicting entries:**

```
[dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
std = { git = "https://github.com/fuellabs/sway", branch = "kayagokalp/1620" }
```

**Comment by mitchmindtree** [comment]
I agree with this, but just want to add that we may want to consider allowing the following:

```toml
[dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
std-kaya = { git = "https://github.com/fuellabs/sway", branch = "kayagokalp/1620", package = "std" }
```

**Comment by JoshuaBatty** [comment]
Hey @kayagokalp just looking for some good first issue for @cr-fuel to pick up. This issue is quite old, has there been any movement on this or is this just yet to be picked up?

**Comment by kayagokalp** [comment]
> Hey @kayagokalp just looking for some good first issue for @cr-fuel to pick up. This issue is quite old, has there been any movement on this or is this just yet to be picked up?

Hey @JoshuaBatty sorry I missed this ping totally. I just tested this and this is still ambiguous so it should be fixed.

For example, using the following manifest file:
```TOML
[project]
authors = ["kayagokalp"]
entry = "main.sw"
license = "Apache-2.0"
name = "deploy-to-beta-4"

[dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
std = { git = "https://github.com/fuellabs/sway", branch = "kayagokalp/3440" }
```

The dependency graph is generated using the second entry and no warning is produced for this shadowing. This should ideally be an error.
