### ISSUE TITLE
Introduce the concept of deployment dependencies to the package manifest file 

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#2931]
After #2893 we will have the basics of the workspace manifest file which will hold just the members of the workspace. We will need a way to declare deployment dependencies for members of the workspace so that while deploying we can build and deploy them in the correct order.

**Comment by mitchmindtree** [comment]
To clarify, I think this should happen in the **package** manifest, not the workspace manifest. E.g. similar to how we currently declare build `[dependencies]` we could also declare `[deploy-dependencies]`:

```toml
[project]
foo = "qux"
# ...

[dependencies]
some-lib = { git = "https://..." }
# ...

[deploy-dependencies]
bar = { path = "../bar" } # Workspace-local contract bar
baz = { path = "../baz" } # Workspace-local contract baz
```

Then, the idea would be that we could access the contract ID of `bar` via `bar::CONTRACT_ID` (or similar, we might want to quickly bike-shed this at the next language sync) within our `foo` project's Sway code which we could achieve by adding `CONTRACT_ID` to the `Namespace` during `forc_pkg::dependency_namespace`.

To begin, we could start by only supporting contracts local to the current workspace, however I don't think there's any reason why we can't point to arbitrary Forc contract projects (e.g. via `git`) as long as we have a standard output location for contract IDs as described i.e. #2930.
