### ISSUE TITLE
docs: invalid testing instructions for `return_data` action

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/sway#4366]
- In `test/src/e2e_vm_tests/test_programs/README.md`, it is written as example: 

```toml
category = "run"
expected_result = { action = "return_data", value = [ 102, 104, 122, 173, 248, 98, 189, 119, 108, 143, 193, 139, 142, 159, 142, 32, 8, 151, 20, 133, 110, 226, 51, 179, 144, 42, 89, 29, 13, 95, 41, 37 ] }
validate_abi = true
```

However, none of the examples have this syntax for `return_data` action, and it doesn't work. It expects a string in such a format (from on of the test projects): 

```toml
category = "run"
expected_result = { action = "return_data", value = "6675656c2d6c61627300000000000000" }
validate_abi = true
```
