### ISSUE TITLE
Revamp forc init

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/sway#5391]
`forc init` generates a default forc project. Currently the files it generates look like this: 

`Forc.toml`
```toml
[project]
authors = ["Sophie"]
entry = "main.sw"
license = "Apache-2.0"
name = "some_name"

[dependencies]
```

`src/main/.sw`
```sway
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}
```

@SilentCicero suggested adding comments to this files with links to our documentation. There are other improvements we can make as well, such as:
- [ ] adding a sample unit test
- [ ] and providing an `--interactive` option that prompts the user to choose options (program type, name, path, whether it's a workspace or not, all with defaults)
- [ ] include `std` dependency by default, and use them in the sample file. Since we don't have a `forc add` function yet, it's good to show an example of how to include dependencies.
- [ ] when `--path` is provided but the directory doesn't exist, offer to create the directory for them
- [ ] Generate a README with links to docs
- [ ] Add a dev-dependency section as well

I propose the default flow generates the following:

`Forc.toml`
```toml
# See more config options: https://docs.fuel.network/docs/forc/manifest_reference/#manifest-reference
[project]
authors = ["Sophie"]
entry = "main.sw"
license = "Apache-2.0"
name = "some_name"

[dependencies]

[dev-dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "master" }
```

`src/main/.sw`
```sway
//! Learn more about contracts: https://docs.fuel.network/docs/sway/sway-program-types/smart_contracts
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        true
    }
}

// Learn more about unit testing: https://docs.fuel.network/docs/sway/testing/unit-testing
#[test]
fn test_contract_call() {
  let caller = abi(MyContract, CONTRACT_ID);
  let result = caller.test_function {}();
  assert_eq(result, true)
}
```

`README.md`
```markdown
# some_name

This Sway project was generated with `forc`. [Read the docs](https://docs.fuel.network/) for more information!
```

For the other program types, the links and test content would be different.
