### ISSUE TITLE
Issues with neovim hover

### ISSUE THREAD

**Issue by codetit4n** [FuelLabs/sway#6091]
I am using `forc-lsp` for sway in neovim. When I try to hover over the `use core::ops::Eq;` trait I get something like this: 
![Screenshot_select-area_20240605114043](https://github.com/FuelLabs/sway/assets/123349376/92686295-6c2b-444a-900d-65192bd7f434)

These are my configs: https://github.com/codetit4n/nvim-config/tree/16d76a8e28e1b5bd28b0ceb1561b0662276f226f
Here is where I have configured the `forc-lsp`: https://github.com/codetit4n/nvim-config/blob/16d76a8e28e1b5bd28b0ceb1561b0662276f226f/lua/codetit4n/lazy/lsp.lua#L80-L101

My forc-toolchain:
```toml
[toolchain]
channel = "testnet"

[components]
forc = "0.60.0"
fuel-core = "0.27.0"
```
