### ISSUE TITLE
Update all deps to be the latest version across the whole repo

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/sway#6179]
Also, it might be worth us migrating to defining dependencies used across multiple workspace members in a `[workspace.dependencies]` section. Eg

```toml
[workspace.dependencies]
clap = "4.5"
dashmap = "6.0"
```

Then in the member projections `Cargo.toml` we can bring them in like

```toml
[dependencies]
clap = { workspace = true }
dashmap = { workspace = true }
```
