### ISSUE TITLE
[forc-pkg] [package-manager] Support pinning forc crates with semver

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#6742]
Once we have the basics of package manager sorted out, we should support pinning dependencies with name and semver version. Just like how cargo supports declaring packages with crate name and versions.

```TOML
[dependencies]
advanced_math = "1.0" // the infra for this is in, but we require the package manager to be functional first.
custom = { git = "https://github.com/FuelLabs/sway/" } // this already works
```
