### ISSUE TITLE
When installing forc with CI, the `mainnet` toolchain is not recognized

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway#7174]
When CI specifies the toolchain as `mainnet`, CI will fail to install with an unknown toolchain error.

```
- name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: mainnet
```

```
Error: Unknown toolchain. Use one of: ['latest', 'nightly', 'beta-1', 'beta-2', 'beta-3']
```
